project:
  version: 0.1
  projectName: Simple
  lowCaseProjectName: simple
  packageName: simple
  swaggerAppName: simple
  urlPrefix: simple
  buildName: simple
  jwt_secret_key: key
server:
  port: 10030
database:
  username: username
  password: password
  address: localhost:3306
  schema: schema
casbin:
  config_file_path: path
admin:
  username: super username
  password: super password
  role: super user role name
  domain: domain
role_config_file_path: role define file
